version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Docker CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      - setup_remote_docker
      - run:
          name: Remove existing Docker container and image
          command: |
            docker container rm -f my_app_container || true
            docker image rm -f my_app_image || true
      - run:
          name: Build Docker image
          command: docker build -t my_app_image .
      - run:
          name: Create and start Docker container
          command: docker run -d --name my_app_container my_app_image
      - run:
          name: Send notification email
          command: |
            sudo apt-get install -y mailutils
            echo "Build and Deploy Job: Success" | mail -s "CircleCI Job Status" your-email@example.com

workflows:
  version: 2
  commit-build:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
