version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

      - run:
          name: Remove existing Docker containers and images
          command: |
            docker-compose down -v --remove-orphans
            docker-compose rm -f -s -v

      - run:
          name: Build and start services
          command: |
            docker-compose up -d --build

      - run:
          name: Send notification email
          command: |
            sudo apt-get install -y mailutils
            echo "Build and Deploy Job: Success" | mail -s "CircleCI Job Status" your-email@example.com

workflows:
  version: 2
  commit-build:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
