version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-deploy:
    executor: docker-executor
    steps:
      - checkout

      # Configuração do Docker Host
      - run:
          name: Set Docker Host
          command: |
            export DOCKER_HOST=tcp://localhost:2375  # Exemplo de configuração para o Docker TCP
            # Comandos restantes do job

      - run:
          name: Remove existing Docker containers and images
          command: |
            docker container rm -f frontend || true
            docker container rm -f backend || true
            docker container rm -f service-node || true
            docker container rm -f db-postgres || true
            docker image rm -f frontend || true
            docker image rm -f backend || true
            docker image rm -f service-node || true
            docker image rm -f db-postgres || true

      # Restante dos passos do seu job

workflows:
  version: 2
  commit-build:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
