version: 2.1

executors:
  docker-executor:
    docker:
      - image: python:3.8

jobs:
  build-and-deploy:
    executor: docker-executor
    steps:
      - checkout

      # Instalação do Docker
      - setup_remote_docker:
          version: 20.10.7

      # Verificação da presença dos Dockerfiles
      - run:
          name: Check for Dockerfiles
          command: |
            ls -la
            if [ ! -f ./app_react/Dockerfile ]; then
              echo "Dockerfile not found in the frontend directory"
              exit 1
            fi
            if [ ! -f ./api/Dockerfile ]; then
              echo "Dockerfile not found in the backend directory"
              exit 1
            fi
            if [ ! -f ./Aula_API_Node/Dockerfile ]; then
              echo "Dockerfile not found in the service-node directory"
              exit 1
            fi

      # Remove containers e imagens existentes
      - run:
          name: Remove existing Docker containers and images
          command: |
            docker container rm -f frontend || true
            docker container rm -f backend || true
            docker container rm -f service-node || true
            docker container rm -f db-postgres || true
            docker image rm -f frontend || true
            docker image rm -f backend || true
            docker image rm -f service-node || true
            docker image rm -f db-postgres || true

      # Build das imagens
      - run:
          name: Build frontend Docker image
          command: |
            docker build -t frontend-image ./app_react
      - run:
          name: Build backend Docker image
          command: |
            docker build -t backend-image ./api
      - run:
          name: Build service-node Docker image
          command: |
            docker build -t service-node-image ./Aula_API_Node

      # Criação e inicialização dos containers
      - run:
          name: Create and start Docker containers
          command: |
            docker run -d --name frontend-container -p 8080:80 frontend-image
            docker run -d --name backend-container -p 8081:80 backend-image
            docker run -d --name service-node-container -p 8082:80 service-node-image

workflows:
  version: 2
  commit-build:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
