version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build-and-deploy:
    executor: docker-executor
    steps:
      - checkout

      # Remove containers e imagens existentes
      - run:
          name: Remove existing Docker containers and images
          command: |
            docker container rm -f frontend || true
            docker container rm -f backend || true
            docker container rm -f service-node || true
            docker container rm -f db-postgres || true
            docker image rm -f frontend || true
            docker image rm -f backend || true
            docker image rm -f service-node || true
            docker image rm -f db-postgres || true

      # Build da imagem
      - run:
          name: Build Docker image
          command: |
            docker build -t myapp-image .

      # Criação e inicialização do container
      - run:
          name: Create and start Docker container
          command: |
            docker run -d --name myapp-container -p 80:80 myapp-image

      # Envio de e-mail de notificação
      - run:
          name: Send notification email
          command: |
            sudo apt-get update && sudo apt-get install -y mailutils
            echo "Build and Deploy Job: Success" | mail -s "CircleCI Job Status" your-email@example.com

workflows:
  version: 2
  commit-build:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
