FROM postgres:latest

# Configure a senha do usuário postgres
ENV POSTGRES_PASSWORD=26062002

# Configure o nome do banco de dados a ser criado
ENV POSTGRES_DB=tb_todo

# Exponha a porta 5432
EXPOSE 5432